# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: builddocker
    jobs:
      - job: builddocker
        steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
          
        - task: Docker@1
          inputs:
            containerregistrytype: 'Azure Container Registry'
            azureSubscriptionEndpoint: 'azure to devops'
            azureContainerRegistry: 'sriramdockerhub.azurecr.io'
            command: 'Build an image'
            dockerFile: '**/Dockerfile'
            imageName: '$(Build.Repository.Name):$(Build.BuildId)'
        
        - task: Docker@1
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'dockerlogin'
            command: 'Push an image'
            imageName: '$(Build.Repository.Name):$(Build.BuildId)'
                 
      