# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: builddocker
    jobs:
      - job: builddocker
        steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
          
       
        - script: |
                images = echo $(Build.SourcesDirectory)/promotion
                docker image pull $images
                docker images
                        
              