# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: builddocker
    jobs:
      - job: builddocker
        steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
          
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerlogin'
            repository: 'testdocker'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
        - script: |
                 echo $containerRegistry/$Containerrepository
        
        